[features]
seeds = false
[programs.localnet]
hello_anchor = "448KahuLdmiQpbrdGziRuQ6Y3mYG3uKWCWzcV3U9UWz6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/yosephks/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
